### ISSUE TITLE
erreur net->brut dernière version d'openfisca

### ISSUE THREAD

**Issue by laem** [sgmap/cout-embauche#288]
Une erreur non explicite lors de la mise à jour d'openfisca nous a fait revenir à cette version qui marche : 

```yaml
france:
  at: 17.2.0

core:
  at: 10.0.0

web_api:
  at: 5.0.1
```
